version:  "3.7"

services:
  microservice:
    build: ./
    ports:
      - "8920:80"
    environment:
      - password_data_base=4eLNFkI9TFCLgYzP
      - user_data_base=dubancsierra
      - server_ip_data_base=note_mongodb
      - appname_data_base=test
      - server_port_data_base=27017
    networks:
      - public
    depends_on:
      - mongo
    hostname: back_end_notes
    volumes:
      - ./src/:/services/apis/back_end_notes/src
  mongo:
    image: mongo
    container_name: note_mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dubancsierra
      - MONGO_INITDB_ROOT_PASSWORD=4eLNFkI9TFCLgYzP
      - MONGO_INITDB_DATABASE=Cluster0
    volumes:
      - ./mongo_data/:/data/db
    networks:
      - public
    ports:
      - 27017:27017
networks:
  public:

