version: '3'

services:
  microservice:
    build: ./
    ports:
      - "8920:80"
    environment:
      - password_data_base=4eLNFkI9TFCLgYzP
      - user_data_base=dubancsierra
      - server_ip_data_base=mongodb
      - appname_data_base=test
      - server_port_data_base=27017
      - kafka_server=""
      - kafka_port_server=""
    networks:
      - public
    depends_on:
      - mongo
    hostname: back_end_notes
  mongo:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dubancsierra
      - MONGO_INITDB_ROOT_PASSWORD=4eLNFkI9TFCLgYzP
      - MONGO_INITDB_DATABASE=Cluster0
    volumes:
      - ./mongo_data/:/data/db
    networks:
      - public
    ports:
      - 27017:27017
networks:
  public: