FROM node:18-alpine

WORKDIR /public/wwww/note-dock

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json /public/wwww/note-dock/package.json
COPY package-lock.json /public/wwww/note-dock/package-lock.json

RUN npm install 
RUN npm install react-scripts@3.4.1 -g 


COPY . ./

CMD [ "npm","start" ]

